'use strict';

/* eslint key-spacing: off */
module.exports = {
  SUCCESS_OK           : 'OK',
  ERROR_PARAMS         : 'ERROR_PARAMS',
  ERROR_UNKNOWN        : 'ERROR_UNKNOWN',
  ERROR_DATA_REPEAT    : 'ERROR_DATA_REPEAT',
  ERROR_SYSTEM_BUSY    : 'ERROR_SYSTEM_BUSY',
  ERROR_NO_PERMISSION  : 'ERROR_NO_PERMISSION',
  ERROR_DATA_NOT_FOUND : 'ERROR_DATA_NOT_FOUND',
  ERROR_ANALYSIS_ENGINE: 'ERROR_ANALYSIS_ENGINE',
};
